/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace FundChain {
      
    export type CampaignStruct = {owner: AddressLike, title: string, description: string, target: BigNumberish, deadline: BigNumberish, amountCollected: BigNumberish}

    export type CampaignStructOutput = [owner: string, title: string, description: string, target: bigint, deadline: bigint, amountCollected: bigint] & {owner: string, title: string, description: string, target: bigint, deadline: bigint, amountCollected: bigint }
  
    }

  export interface FundChainInterface extends Interface {
    getFunction(nameOrSignature: "campaigns" | "createCampaign" | "donateToCampaign" | "donors" | "getCampaigns" | "getDonors" | "withdraw"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'campaigns', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createCampaign', values: [string, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'donateToCampaign', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'donors', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCampaigns', values?: undefined): string;
encodeFunctionData(functionFragment: 'getDonors', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'campaigns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'donateToCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'donors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCampaigns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDonors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  

  export interface FundChain extends BaseContract {
    
    connect(runner?: ContractRunner | null): FundChain;
    waitForDeployment(): Promise<this>;

    interface: FundChainInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    campaigns: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint] & {owner: string, title: string, description: string, target: bigint, deadline: bigint, amountCollected: bigint }],
      'view'
    >
    

    
    createCampaign: TypedContractMethod<
      [_title: string, _description: string, _target: BigNumberish, _deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    donateToCampaign: TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    donors: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getCampaigns: TypedContractMethod<
      [],
      [FundChain.CampaignStructOutput[]],
      'view'
    >
    

    
    getDonors: TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'campaigns'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint] & {owner: string, title: string, description: string, target: bigint, deadline: bigint, amountCollected: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'createCampaign'): TypedContractMethod<
      [_title: string, _description: string, _target: BigNumberish, _deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'donateToCampaign'): TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'donors'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getCampaigns'): TypedContractMethod<
      [],
      [FundChain.CampaignStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getDonors'): TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }