/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FundChain } from './FundChain.js';
export * as factories from './factories/index.js';
export { FundChain__factory } from './factories/FundChain__factory.js';